### ISSUE TITLE
Readme Links Dead

### ISSUE THREAD

**Issue by ledbthand** [apocalyptech/bl3-cli-saveedit#12]
Both of the Readme links seem to be dead.  Thank you for your constant updates. :)

**Comment by apocalyptech** [comment]
Hello, thanks!

I assume you mean when the project's viewed at pypi.org, yeah?  I see what you mean.  I'll have to change those to be absolute links so that they work over there as well.  Thanks for the report!  I was gonna add a couple more minor things in the next few days, so I'll get that fixed in the next release.  :)

Cheers!

**Comment by ledbthand** [comment]
Awesome!  Cheers m8!

**Comment by apocalyptech** [comment]
Okay, that's been checked in, though I'm not planning on doing another "official" release until next week when DLC3 drops, so the PyPI links will remain broken until then.

Thanks again for the report!

**Comment by apocalyptech** [comment]
Hah, well, I actually had another update that I'd wanted to get out sooner, after all, so this should be fixed @ PyPi already.  :)
