### ISSUE TITLE
Feature Request: Copy TVHM State To NVHM

### ISSUE THREAD

**Issue by Xen0byte** [apocalyptech/bl3-cli-saveedit#19]
Most people blitz through NVHM so they can play TVHM. It would be nice to be able to update the NVHM state with the progress from TVHM.

**Comment by apocalyptech** [comment]
Hello - this one's actually already in there: https://github.com/apocalyptech/bl3-cli-saveedit/blob/master/README-saves.md#copy-nvhm-state-to-tvhm

Cheers!

**Comment by Xen0byte** [comment]
Hi @apocalyptech, this feature request is the reverse of that. TVHM > NVHM, not NVHM > TVHM.

**Comment by apocalyptech** [comment]
Oh, so it is, sorry about that.  :)  Sure, I can get that added in in a bit, though I'm heading out for the weekend at the moment.

**Comment by Xen0byte** [comment]
Thanks, I was out and about on holiday as well. Cheers for reopening this.

**Comment by apocalyptech** [comment]
Heh, well I did implement this awhile ago but hadn't actually gotten around to testing it properly, and then sort of forgot that it was still sitting there.  I just pushed out an update with support for today's patch (Vault Card 3) which does *not* include the TVHM-copying functionality, since I still haven't tested it.  I'll try and get that worked out before next week, though, and push out a new version which has that enabled.  Cheers!

**Comment by Xen0byte** [comment]
That's awesome! Cheers.

**Comment by apocalyptech** [comment]
Okay, well, two years is a pretty decent time to finish up implementing a pretty minor feature, yeah?  Right?

Anyway, was dusting this thing off thanks to yesterdays cosmetics patch, and noticed that this thing was still in a mostly-implemented but not-at-all tested state.  Apologies again!  I did get some actual testing in today, and it looks like it should be in good shape, so this is finally committed to the github.  It'll be included in the forthcoming 1.17.0 release, which I'm hoping to get out this afternoon yet.

Cheers!
