### ISSUE TITLE
Can't find save files

### ISSUE THREAD

**Issue by bimboozled** [apocalyptech/bl3-cli-saveedit#23]
Hi,
I'm trying to delete a bugged side mission and I'm having some issues finding/editing the save files. My coding knowledge is limited, so sorry if these are very basic questions haha. What exactly is meant by the command "bl3-save-info --all-missions old.sav"? I assume that the "old" part is just a placeholder, right? I can't figure out what to put there, as I'm getting an error "No such file or directory: 'old.sav'". 

Also, looking at the program in file explorer, it appears that vast majority of the data is stored as very large .PAK files - I don't see any .sav files. They all have generic names with no indication of what's in each of them. Do I need to extract all of these? There are 425 files for a total of 93 GB to sift through so I'm hoping that I don't actually need to do this.

Thanks in advance!

**Comment by apocalyptech** [comment]
Heya -- your savegames are stored in a different place than the pakfiles.  No extraction necessary!  You should be able to find the saves in, I think, `My Documents\My Games\Borderlands 3\Saved\SaveGames\<numbers>`, inside your user's homedir.  And yeah, to use the utility you give it an "old" filename (ie: the savefile you want to edit), and a "new" filename (ie: the edited version).  You can use the same filename for both old+new if you want it to directly overwrite -- just make sure that you're making backups!

The easiest way to run it would be to use `cd` to go "into" that savegame dir itself, so that you can just use filenames like `2.sav` or `12.sav` for the filenames, rather than having to put in long paths like `C:\Users\<username>\My Documents\....` each time.

Good luck!

**Comment by bimboozled** [comment]
Got it, I guess the issue was that I was accidentally apparently in the steam parent directory instead of my personal user directory, so there weren't any save files visible at first. Thanks for the help!
