### ISSUE TITLE
Feature Request: Batch modifying Mayhem level anointments

### ISSUE THREAD

**Issue by unlimitedsola** [apocalyptech/bl3-cli-saveedit#5]
With Mayhem 2.0 coming out, We'd like to have a feature that modifies all gears' mayhem level in the Vault & Backpack. Just like what we did for the gears' level.

**Comment by apocalyptech** [comment]
Yep, for sure!  I've already been planning on doing that; just have to actually put bits in here to start parsing item parts (since the mayhem levels are technically just extra parts on the gear).  I'm hoping to have it out by the end of the weekend, though no promises.  :)

Thx for the suggestion!  I'll update here when I've got it out.

**Comment by apocalyptech** [comment]
Hello - FYI, I've got some commits checked in which should do it.  Use with care and take backups, but I think they *should* be good.  (Only implemented in the save editor; profile/bank doesn't do it yet.)

I'm not *super* happy with the implementation so I'll probably be doing some rearranging.  Will probably be a few days before it gets released officially.

**Comment by apocalyptech** [comment]
Okay, I went ahead and released 1.5.0 which has the mayhem stuff in there.  In the end the implementation didn't really change much; it's inefficient but lets the thing process items fairly atomically, so I didn't bother trying to refactor it.  Enjoy!  Let me know if you encounter problems!

**Comment by unlimitedsola** [comment]
Appreciate your amazing work!
