### ISSUE TITLE
JSON import broken when writing new file

### ISSUE THREAD

**Issue by NoneGiven** [apocalyptech/bl3-cli-saveedit#8]
JSON import works when overwriting an existing .sav file, but does not work when attempting to create a new file. This applies to both save and profile importing. ~~Both work as expected when importing ProtoBuf.~~

### Version

1.5.0

### Steps to reproduce

```
bl3-save-edit 1.sav new.json -o json
bl3-save-import-json -j new.json -t new.sav
```

### Expected results

The second command creates `new.sav`.

### Actual results

```Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\Scripts\bl3-save-import-json.exe\__main__.py", line 7, in <module>
  File "c:\program files\python36\lib\site-packages\bl3save\cli_import_json.py", line 62, in main
    raise Exception('Filename {} does not exist'.format(args.filename_to))
Exception: Filename new.sav does not exist
```

**Comment by apocalyptech** [comment]
Ah, y'know, I should probably be more clear about that in the docs - when importing JSON (or Protobuf, for that matter), it does currently need an *existing* savefile to import to, even though you're basically overwriting the whole thing.

I agree it's a bit inconsistent, since it's pretty much the only time the utils *expect* to overwrite something, as opposed to the others which do everything they can to not do that.  :)  I'll look at updating the docs, and possibly altering the util so that it's a bit more inline with the rest of the utilities.  (Though I've also been thinking I should probably implement a write-in-place option for the rest, too...)

**Comment by NoneGiven** [comment]
Whoops, not sure why I thought it worked for ProtoBuf.

Calling it out in the docs is good enough. Now that I think about it for a second, it does make sense since you're only reading/writing the save payload and not the GVAS header.

**Comment by apocalyptech** [comment]
Pushed some docs changes to this effect, but I'm honestly just wondering if it'd make sense to alter these so that they *do* just let you create a brand new file from scratch.  That'd mean me collecting a bit of valid GVAS information to use for from-scratch files, of course...  Still, perhaps that'd be a better way forward.  Gonna let this sit in my brain for a bit.

**Comment by apocalyptech** [comment]
Okay, so in the end I think I'll probably leave the JSON/Protobuf import commands the way they are.  That is, in the end, just down to laziness - To support creating saves from scratch, I'd have to take a closer look at all the GVAS stuff in there and at least try to do the right thing in relation to those.  And I'm afraid I just don't care enough to spend the time on it.  :)  So!  We'll just make do with the extra stuff in the docs that I added.

In re: having the editing utils write to the same file they're editing (which I realize is a bit offtopic for the Issue, but eh), I'd *thought* I'd put in a check to disallow that, but it looks like I never did, and the app will happily overwrite the same file you're working on, if you specify the filename twice.  So!  That's good enough for me.  I'm gonna change the wording of the `overwrite?` prompt a bit, when the same file's specified twice, but otherwise that too is good enough for me.

Thx again for the report!
