### ISSUE TITLE
Guardian rank profile editing

### ISSUE THREAD

**Issue by ensiform** [apocalyptech/bl3-cli-saveedit#9]
So I know currently there is no guardian rank editing options. As I'm not sure whether this is stored in the profile save at all. But last night I had a PC crash which seems to have been mid write of my profile during play and it corrupted my profile to a weird state. I still have my bonus stats unlocked, and each top guardian tree lists the correct number of tokens that were allocated in each tree. However my guardian rank is reset to 1 and none of the perks appear to be capable of being re-enabled at the moment. Thankfully the character save was unaffected.

Any ideas? I guess I could try consulting gbx/2k but just was curious if I can fix it myself eventually via some means of figuring out an approximate rank that is necessary for the number of alleged unlocked tokens.

**Comment by NoneGiven** [comment]
Guardian Rank is stored in the following format in the profile:

```protobuf
message GuardianRankRewardSaveGameData {
  int32 num_tokens = 1;
  string reward_data_path = 2;
}
message GuardianRankProfileData {
  int32 available_tokens = 1;
  repeated GuardianRankRewardSaveGameData rank_rewards = 2;
  int32 guardian_rank = 3;
  int32 guardian_experience = 4;
  int32 guardian_reward_random_seed = 5;
  int64 new_guardian_experience = 6;
}
```

I don't think you need to change the experience; AFAICT `guardian_experience` is just the current amount you have towards the next level, and `new_guardian_experience` is the amount you need to reach for that level.

It sounds like what you need to fix is just setting `guardian_rank` to the combined number of tokens you've spent on the reward trees. I wasn't able to find where those rewards are tracked (`rank_rewards` are the bonus stats), but presumably that data is fine since you can see the correct numbers on the trees.

**Comment by NoneGiven** [comment]
Strangely, it seems like Guardian Rank data is stored both in the profile and the character save. If you export these files to JSON and make some careful edits, then reimport the JSON back into the save and profile, you can probably fix this issue (make backups first!).

Look for the `guardian_rank` section in the profile and the `guardian_rank_character_data` section in the save.

![image](https://user-images.githubusercontent.com/2163967/80778631-10d3ce80-8b37-11ea-89ea-17eb313b4cb6.png)

![image](https://user-images.githubusercontent.com/2163967/80778658-1e895400-8b37-11ea-8d7d-a55b3b535d28.png)

Based on your description of the issue, I think you can you fix it by editing the value of `guardian_rank` (in both files) to the combined number of tokens you spent in the reward trees.

If the experience amounts look wrong then those also might need updating, but I'm not certain about the relationship between those values. Maybe post yours for comparison?

**Comment by apocalyptech** [comment]
So yeah, pretty much what @NoneGiven said - the JSON export/import capability could probably get you back to where you want to be.

You could also use FromDarkHell's Profile Editor instead, if you want; that'll let you just plug in however much Guardian Rank you want: https://github.com/FromDarkHell/BL3ProfileEditor/releases

**Comment by ensiform** [comment]
So it seems the guardian perks have fixed themselves, but still need to do the above recommendations for fixing the guardian rank. Thanks

**Comment by apocalyptech** [comment]
Yeah, it's a bit weird that Guardian Rank is stored in both the profile and the savegame, though your case here is probably why they did it that way.  It's probably *because* it's stored in both locations that you got it back; when you loaded the savegame again, it noticed that your `profile.sav` GR was empty, and so it copied the savegame info over to the profile.  This was actually causing all kinds of havoc originally, because the game would end up somewhat indiscriminately copying over savegame GR, and folks were having their profile GR "infected" by modded savegames that they were downloading online, etc.

I think nowadays it's smarter about it -- if you have at least one point of GR in the profile, it won't overwrite it with the savegame version.  I still have no idea how exactly the two relate to each other, though.  If one gets updated but not the other, etc.  (It wouldn't be hard to figure out, given the JSON export, but I've just not taken the time to do so.)

**Comment by apocalyptech** [comment]
Okay, anyway -- I guess I'll close this out.  If there's anything else, just let me know!
